apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:
      - name: airflow
        image: openweather-airflow:1.0.0
        env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: "LocalExecutor"
        - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
          value: "postgresql+psycopg2://airflow:airflow@postgres:5432/metadata"
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: openweather-api-key
              key: key
        - name: ROOT_PATH
          value: /opt/airflow
        volumeMounts:
          - name: datalake
            mountPath: /opt/airflow/data
      volumes:
        - name: datalake
          persistentVolumeClaim:
            claimName: datalake